Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Info  { param($m) Write-Host "  $m"      -ForegroundColor Cyan   }
function OK    { param($m) Write-Host " [OK] $m"  -ForegroundColor Green  }
function Warn  { param($m) Write-Host " [!!] $m"  -ForegroundColor Yellow }
function Step  { param($m) Write-Host "`n=== $m ===" -ForegroundColor Magenta }

$root     = Split-Path $MyInvocation.MyCommand.Path -Parent
$frontend = Join-Path $root 'frontend'
$cfgPath  = Join-Path $root 'firebase-applet-config.json'
$firebaseJsonPath = Join-Path $root 'firebase.json'
$indexesPath = Join-Path $root 'firestore.indexes.json'

Write-Host ""
Write-Host "  HOLO AstroCRM - Firebase Setup Script" -ForegroundColor DarkCyan
Write-Host ""

Step "STEP 1/5 - Read firebase-applet-config.json"
if (-not (Test-Path $cfgPath)) { Write-Host "[ERR] $cfgPath not found" -ForegroundColor Red; exit 1 }
$cfg        = Get-Content $cfgPath -Raw | ConvertFrom-Json
$PROJECT_ID = $cfg.projectId
$APP_ID     = $cfg.appId
$API_KEY    = $cfg.apiKey
$AUTH_DOMAIN = $cfg.authDomain
$DB_ID      = $cfg.firestoreDatabaseId
$STORAGE    = $cfg.storageBucket
$SENDER_ID  = $cfg.messagingSenderId
OK "Project: $PROJECT_ID"
OK "Firestore DB: $DB_ID"

Step "STEP 2/5 - Write frontend/.env.local"
$envContent = "# Firebase (auto-generated by setup_firebase.ps1)`n" +
"VITE_FIREBASE_API_KEY=$API_KEY`n" +
"VITE_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN`n" +
"VITE_FIREBASE_PROJECT_ID=$PROJECT_ID`n" +
"VITE_FIREBASE_STORAGE_BUCKET=$STORAGE`n" +
"VITE_FIREBASE_MESSAGING_SENDER_ID=$SENDER_ID`n" +
"VITE_FIREBASE_APP_ID=$APP_ID`n" +
"VITE_FIREBASE_FIRESTORE_DB=$DB_ID`n" +
"VITE_API_URL=https://astrocrm-production.up.railway.app`n"
$envPath = Join-Path $frontend '.env.local'
[System.IO.File]::WriteAllText($envPath, $envContent, [System.Text.Encoding]::UTF8)
OK "Written: $envPath"

$firebaseJson = @"
{
  "firestore": {
    "database": "$DB_ID",
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }
}
"@
[System.IO.File]::WriteAllText($firebaseJsonPath, $firebaseJson, [System.Text.Encoding]::UTF8)
OK "Written: $firebaseJsonPath"

if (-not (Test-Path $indexesPath)) {
  [System.IO.File]::WriteAllText($indexesPath, "{`n  `"indexes`": []`n}`n", [System.Text.Encoding]::UTF8)
  OK "Written: $indexesPath"
}

Step "STEP 3/5 - Check / install firebase-tools"
$skipDeploy = $false
$firebaseCmd = Join-Path $env:APPDATA 'npm\firebase.cmd'
if (-not (Test-Path $firebaseCmd)) {
  Info "Installing firebase-tools globally..."
  & "$env:ProgramFiles\nodejs\npm.cmd" install -g firebase-tools --no-audit --no-fund
}
if (Test-Path $firebaseCmd) { $ver = & $firebaseCmd --version 2>&1; OK "firebase-tools $ver" }
else                       { Warn "firebase-tools not found after install. Will skip deploy step."; $skipDeploy = $true }

Step "STEP 4/5 - Deploy Firestore rules"
if (-not $skipDeploy) {
  Push-Location $root
  $loginState = & $firebaseCmd login:list 2>&1
  if ($loginState -match 'No authorized accounts') {
    Info "No Firebase login detected. Opening browser for authentication..."
    & $firebaseCmd login
  }
  Info "Running: firebase deploy --only firestore:$DB_ID --project $PROJECT_ID"
  Write-Host ""
  & $firebaseCmd deploy --only "firestore:$DB_ID" --project $PROJECT_ID
  if ($LASTEXITCODE -eq 0) { OK "Firestore rules deployed to $PROJECT_ID" }
  else { Warn "Deploy exited with code $LASTEXITCODE. Run manually: `"$firebaseCmd`" deploy --only firestore:$DB_ID --project $PROJECT_ID" }
  Pop-Location
} else {
  Warn "Skipped. Run manually: `"$firebaseCmd`" deploy --only firestore:$DB_ID --project $PROJECT_ID"
}

Step "STEP 5/5 - Railway environment variables"
Write-Host ""
Write-Host "  Add these vars in Railway (Dashboard -> Variables):" -ForegroundColor White
Write-Host "  VITE_FIREBASE_API_KEY             = $API_KEY"            -ForegroundColor Yellow
Write-Host "  VITE_FIREBASE_AUTH_DOMAIN         = $AUTH_DOMAIN"        -ForegroundColor Yellow
Write-Host "  VITE_FIREBASE_PROJECT_ID          = $PROJECT_ID"         -ForegroundColor Yellow
Write-Host "  VITE_FIREBASE_STORAGE_BUCKET      = $STORAGE"            -ForegroundColor Yellow
Write-Host "  VITE_FIREBASE_MESSAGING_SENDER_ID = $SENDER_ID"          -ForegroundColor Yellow
Write-Host "  VITE_FIREBASE_APP_ID              = $APP_ID"             -ForegroundColor Yellow
Write-Host "  VITE_FIREBASE_FIRESTORE_DB        = $DB_ID"              -ForegroundColor Yellow
Write-Host "  VITE_API_URL                      = https://astrocrm-production.up.railway.app" -ForegroundColor Yellow
Write-Host ""

$railCmd = Get-Command railway -ErrorAction SilentlyContinue
if ($railCmd) {
  Info "railway CLI found - setting vars automatically..."
  $vars = @{
    "VITE_FIREBASE_API_KEY"               = $API_KEY
    "VITE_FIREBASE_AUTH_DOMAIN"           = $AUTH_DOMAIN
    "VITE_FIREBASE_PROJECT_ID"            = $PROJECT_ID
    "VITE_FIREBASE_STORAGE_BUCKET"        = $STORAGE
    "VITE_FIREBASE_MESSAGING_SENDER_ID"   = $SENDER_ID
    "VITE_FIREBASE_APP_ID"                = $APP_ID
    "VITE_FIREBASE_FIRESTORE_DB"          = $DB_ID
    "VITE_API_URL"                        = "https://astrocrm-production.up.railway.app"
  }
  foreach ($kv in $vars.GetEnumerator()) {
    $res = & railway variables set "$($kv.Key)=$($kv.Value)" 2>&1
    if ($LASTEXITCODE -eq 0) { OK "railway: $($kv.Key)" }
    else { Warn "Failed to set $($kv.Key): $res" }
  }
} else {
  Warn "railway CLI not found. Add vars manually or: npm install -g @railway/cli"
}

Write-Host ""
Write-Host "  IMPORTANT: Enable Email/Password auth in Firebase Console:" -ForegroundColor Cyan
Write-Host "  https://console.firebase.google.com/project/$PROJECT_ID/authentication/providers" -ForegroundColor Cyan
Write-Host "  -> Sign-in providers -> Email/Password -> Enable -> Save" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Done!" -ForegroundColor Green